import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { Cardbox } from '../components/cardbox/cardbox.module'
import { About } from '../components/about/about.module'
import { Squares } from '../components/squares/squares.module'
import { Services } from '../components/services/services.module'
import { Footer } from '../components/footer/footer.module'
import { Header } from '../components/header/header.module'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>The Brink Assingnment</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="./asset/SuisseIntL/Suisse_Int'l.otf"
          rel="stylesheet"
        />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* Header Block */}
      <header >
        <Header />

      </header>
      {/* End of Header Block */}

      <main className={styles.main}>

        {/* Cards Block */}
        <Cardbox />
        {/* End of Cards Block */}


        {/* About Block */}
        <About />
        {/* End of About Block */}


        {/* Grid Block */}
        <Squares />
        {/* End of Grig Block */}

        {/* Services Block */}
        <Services />
        {/* End of Service Block */}

      </main>


      <footer>
        <Footer />
      </footer>
    </div>
  )
}
